services:
  - type: web
    name: flowmind-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_SHEETS_CREDENTIALS
        sync: false
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_APP_PASSWORD
        sync: false
      - key: JIRA_DOMAIN
        sync: false
      - key: JIRA_EMAIL
        sync: false
      - key: JIRA_API_TOKEN
        sync: false
      - key: JIRA_PROJECT_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
